name: Generate SAT Lessons

on:
  push:
    paths:
      - 'skills/**/lesson.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-pptx reportlab

    - name: Generate lessons
      run: |
        for file in $(find skills -name lesson.md); do
          echo "Processing $file"
          python generate_lessons.py $file
        done

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add skills
        git commit -m "Auto-generate lesson decks and index [skip ci]" || echo "No changes to commit"
        git push
